# Generated by Django 4.2.17 on 2025-01-16 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('payment_dt', models.DateTimeField(editable=False)),
                ('payment_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('total_payment', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sub_total', models.DecimalField(decimal_places=2, editable=False, max_digits=7)),
                ('tax_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('MOBILE', 'MOBILE')], editable=False, max_length=32)),
                ('served_by', models.CharField(blank=True, help_text='Staff or cashier handling the transaction', max_length=100, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cart.order')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=125)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=7, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tax_applied', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('qty', models.IntegerField(default=0, editable=False, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='cart.order')),
                ('payment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='payment.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Orders',
            },
        ),
    ]
