# Generated by Django 4.2.17 on 2025-01-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Amount paid in Ksh', max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='qty',
            field=models.IntegerField(default=0, editable=False, help_text='Quantity of items', null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='tax_applied',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Tax applied in Ksh', max_digits=10, null=True),
        ),
    ]
