# Generated by Django 4.2.17 on 2025-01-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymentorder_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_dt',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('MOBILE', 'MOBILE')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
