# Generated by Django 4.2.17 on 2025-01-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=125, null=True),
        ),
    ]
