# Generated by Django 4.2.17 on 2025-01-17 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_customer_name'),
        ('payment', '0005_alter_paymentorder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cart.order'),
        ),
    ]
