# Generated by Django 4.2.17 on 2025-01-14 00:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_category', models.CharField(max_length=32, unique=True)),
                ('tax_desc', models.TextField(blank=True)),
                ('tax_percentage', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Tax Information',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True)),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount', max_digits=5)),
                ('qty', models.IntegerField(default=0, help_text='Available stock quantity')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Buying price', max_digits=10)),
                ('unit', models.CharField(blank=True, default='piece', help_text='Unit of measurement (e.g., piece, plate, pair)', max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=125, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Volume in liters (e.g., 1.0 L)', max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams (e.g., 500g)', max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.subcategory')),
                ('tax_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='inventory.taxcategory')),
            ],
        ),
    ]
