# Generated by Django 4.2.17 on 2025-01-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
    ]
