# Generated by Django 4.2.17 on 2025-01-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_menuitem_unit_menuitem_volume_menuitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='currency',
            field=models.CharField(default='Ksh', max_length=3),
        ),
    ]
