# Generated by Django 4.2.17 on 2025-01-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_menuitem_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='guest', max_length=100, null=True),
        ),
    ]
